site_name: e-Título

repo_url: https://github.com/Requisitos-de-Software/2020.2-e-Titulo
repo_name: 'e-Título'

theme:
  name: material
  language: 'pt'
  logo: 'assets/icons/eTitulo.png'
  favicon: 'assets/icons/codercat.png'

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
      - Rich Pictures: pre_rastreabilidade/rich_pictures.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md